FROM postgres:15

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-15-similarity \
        postgresql-contrib \
        python3 \
        python3-pip \
    && pip3 install --no-cache-dir --break-system-packages \
        --trusted-host pypi.org \
        --trusted-host pypi.python.org \
        --trusted-host files.pythonhosted.org \
        psycopg2-binary \
        tqdm \
        python-dotenv \
        python-dotenv \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /scripts