# =============================================================
# tabelas.conf — gerado automaticamente por gerar_conf.py
# Formato: tabela | coluna_data | dias | limit
# =============================================================

carteirabkpnexteavm |  |  | 500
depara_amigavel_20230324 |  |  | 500
depara_amigavel_deepcenter |  |  | 500
depara_honda |  |  | 500
depara_telecobranca_20230324 |  |  | 500
depara_telecobranca_deepcenter |  |  | 500
dp_amigavel |  |  | 500
esdeepcenter_acionamento_bradesco_124552 |  |  | 500
esdeepcenter_acompanhamento_campanha |  |  | 500
esdeepcenter_acompanhamentoagente |  |  | 500
esdeepcenter_acompanhamentoskill |  |  | 500
esdeepcenter_auditoria_bradesco_amigavel |  |  | 500
esdeepcenter_auditoria_bradesco_digital |  |  | 500
esdeepcenter_auditoria_bradesco_telecobranca |  |  | 500
esdeepcenter_auditoria_folowup_bradesco |  |  | 500
esdeepcenter_auditoria_ocorrencia_bradesco |  |  | 500
esdeepcenter_auditoria_ocorrencia_bradesco_digital |  |  | 500
esdeepcenter_carteira_351 |  |  | 500
esdeepcenter_carteira_amigavel |  |  | 500
esdeepcenter_carteira_digital |  |  | 500
esdeepcenter_carteira_telecobranca |  |  | 500
esdeepcenter_crmdac_351 |  |  | 500
esdeepcenter_crmdac_amigavel |  |  | 500
esdeepcenter_crmdac_telecobranca |  |  | 500
esdeepcenter_crmjur |  |  | 500
esdeepcenter_digital_351 |  |  | 500
esdeepcenter_digital_amigavel |  |  | 500
esdeepcenter_digital_telecobranca |  |  | 500
esdeepcenter_metadados |  |  | 500
esdeepcenter_metadados_519 |  |  | 500
esdeepcenter_multicanal_351 |  |  | 500
esdeepcenter_multicanal_amigavel |  |  | 500
esdeepcenter_multicanal_telecobranca |  |  | 500
esdeepcenter_retorno_bradesco |  |  | 500
esdeepcenter_tempooperacional_amigavel |  |  | 500
esdeepcenter_tempooperacional_consorcio |  |  | 500
esdeepcenter_tempooperacional_telecobranca |  |  | 500
ocorrencias_bradesco_p2_amigavel |  |  | 500
ocorrencias_bradesco_p2_tele |  |  | 500
ocorrencias_bradesco_p3 |  |  | 500
remocaocarteira346 |  |  | 500
temp_acionamento_positivo |  |  | 500
tmp_json_esdeepcenter_crmdac_3 |  |  | 500
ura_bradesco |  |  | 500
